### ISSUE TITLE
"Bad Request: The username you entered doesn't appear to belong to an account." error

### ISSUE THREAD

**Issue by Ladykilljoy** [taengstagram/instagram-livestream-downloader#1]
## Please read the following instructions carefully

- Issues submitted without this template format will be **ignored**.
- I can't help you with python / ffmpeg installation problems so issues related to those will probably not get a response from me.
- Please read the questions asked and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] - no spaces).
- Do not post screenshots of text errors or logs.
- Use the Preview tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/README.md)
- [x] [Searched](https://github.com/taengstagram/instagram-livestream-downloader/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Make sure you have the latest version: v0.2.4

### Purpose of your issue:
- [x] Bug report (problems/errors)
- [ ] Question
- [ ] Other

### For a bug report, you **must** include the command used and a complete output/error log.

Command:

```
livestream_dl -u 'ams_sone' -p '<PASSWORD>' 'nuryerlitas' -verbose
```

Complete Output/Error Log:

```
[92mINSTAGRAM LIVESTREAM DOWNLOADER (v0.2.4) [python=2.7.13,win32][0m
Executing: "ffmpeg -version"[0m
ffmpeg version N-84814-gad7aff0 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 6.3.0 (GCC)
configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
libavutil      55. 52.100 / 55. 52.100
libavcodec     57. 86.103 / 57. 86.103
libavformat    57. 68.100 / 57. 68.100
libavdevice    57.  3.101 / 57.  3.101
libavfilter     6. 78.101 /  6. 78.101
libswscale      4.  3.101 /  4.  3.101
libswresample   2.  4.100 /  2.  4.100
libpostproc    54.  2.100 / 54.  2.100
Exit code: 0[0m
[92m=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-[0m
REQUEST: https://i.instagram.com/api/v1/si/fetch_headers/?challenge_type=signup&guid=aac99a42161611e78d2e1c6f65c54517 POST[0m
DATA: [0m
REQUEST: https://i.instagram.com/api/v1/accounts/login/ POST[0m
DATA: ig_sig_key_version=4&signed_body=e909d735d66e9b81a37ce0bebbd4d1438e777451be73e381ec3d2efaf50e4777.%7B%22username%22%3A%22%27ams_sone%27%22%2C%22guid%22%3A%22aac99a40-1616-11e7-a2ec-1c6f65c54517%22%2C%22phone_id%22%3A%2251b5014f-92cb-c8b6-9ce9-0191f83fb9af%22%2C%22_csrftoken%22%3A%22hsq46IrJWA3Q1AgrfHcMX5cDeaTIKUev%22%2C%22login_attempt_count%22%3A%220%22%2C%22password%22%3A%22%27<PASSWORD>%27%22%2C%22device_id%22%3A%22android-aac99a41161611e7%22%7D[0m
RESPONSE: 400 {"invalid_credentials": true, "error_title": "Incorrect Username", "error_type": "invalid_user", "message": "The username you entered doesn't appear to belong to an account. Please check your username and try again.", "status": "fail", "buttons": [{"action": "dismiss", "title": "Try Again"}]}[0m
[91mClientError Bad Request: The username you entered doesn't appear to belong to an account. Please check your username and try again. (Code: 400, Response: {"invalid_credentials": true, "error_title": "Incorrect Username", "error_type": "invalid_user", "message": "The username you entered doesn't appear to belong to an account. Please check your username and try again.", "status": "fail", "buttons": [{"action": "dismiss", "title": "Try Again"}]})[0m
```

### Describe your issue

I pick a random user that has an instagram live ongoing for testing purposes. With the "-p" argument I make sure that my password is correctly typed(which it is) but despite trying multiple accounts that I can correctly log into Instagram with, I get this same error. I tried without the "-p" argument without success and I also tried without a target account, but it makes no difference.

**Comment by taengstagram** [comment]
This is interesting. Windows must be parsing things a little differently.

Can you try 2 things:
1. With double quotes instead of single quotes, e.g.
``livestream_dl -u "ams_sone" -p "<PASSWORD>" "nuryerlitas"``
2. Without any quotes at all (assuming you don't have spaces or semi-colons in your password, e.g.
``livestream_dl -u ams_sone -p PASSWORD nuryerlitas``

**Comment by Ladykilljoy** [comment]
Both of your suggestions solved the issue(my password has no spaces or semi-colons only a special character), I should have guessed that too, never used single quotes in windows before.

The video downloaded properly, working great.

**Comment by taengstagram** [comment]
Glad to hear that. I'll update the docs to use double-quotes since the the difference on other OSes is way more subtle.
