### ISSUE TITLE
Feature request: Collect all comments from a livestream

### ISSUE THREAD

**Issue by dvingerh** [taengstagram/instagram-livestream-downloader#10]
## Please read the following instructions carefully

- Issues submitted without this template format will be **ignored**.
- I can't help you with python / ffmpeg installation problems so issues related to those will probably not get a response from me.
- Please read the questions asked and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] - no spaces).
- Do not post screenshots of text errors or logs.
- Use the Preview tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/README.md)
- [x] Read the [FAQ](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/FAQ.md)
- [x] [Searched](https://github.com/taengstagram/instagram-livestream-downloader/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Make sure you have the latest version: v0.3.1

### Purpose of your issue:
- [ ] Bug report (problems/errors)
- [ ] Question
- [x] Other

### Describe your issue

Is it possible to implement a feature that collects *all* comments from a livestream?
Maybe a config option like `collectallcomments=1` which will override the other comment settings and save all comments from a livestream to a .txt file.

**Comment by taengstagram** [comment]
What is the point of this?
It is possible but I'm not interested to do so. 

- For popular/celebrity streams, this can be excessive.
- Comments currently collected are converted into an accompanying .srt file that can be viewed in most common video players. This becomes meaningless if there are too many comments.

**Comment by dvingerh** [comment]
> What is the point of this?

When for example the user who hosts the livestream answers questions from comments it would be nice to know what people commented.

**Comment by taengstagram** [comment]
If the stream is popular, the comments saved are still going to be difficult to view with a conventional player. IG gets around this by presenting comments in what is basically a vertically scrolling ticker.

I won't implement this but you're free to fork and customise this for your use case. It shouldn't​ require major changes so good luck!

**Comment by NabiKAZ** [comment]
@taengstagram @notcammy 

The current implementation about convert specific comments to a SRT file maybe was useful.

But I agree with notcammy's point more.

Filter comments by specific users not be useful, We need have more or all user's comments, If there is problem with SRT, no problem, can store it by timestamp in a JSON file.
This can be new optional feature.
