### ISSUE TITLE
Can't download livestream from a private account

### ISSUE THREAD

**Issue by arieoo** [taengstagram/instagram-livestream-downloader#11]
## Please read the following instructions carefully

- Issues submitted without this template format will be **ignored**.
- I can't help you with python / ffmpeg installation problems so issues related to those will probably not get a response from me.
- Please read the questions asked and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] - no spaces).
- Do not post screenshots of text errors or logs.
- Use the Preview tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/README.md)
- [x] Read the [FAQ](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/FAQ.md)
- [x] [Searched](https://github.com/taengstagram/instagram-livestream-downloader/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Make sure you have the latest version: v0.3.4

### Purpose of your issue:
- [ ] Bug report (problems/errors)
- [x] Question
- [ ] Other

### Describe your issue

Hi, i just noticed this morning that i can't download livestream from private acc that i'm not following, is it from Instagram or because the new update? because if i'm not wrong, i still can do that a few days ago. Thanks.

**Comment by taengstagram** [comment]
If you're not following the private account, I doubt very much that IG would have returned any stream information. This would be a serious privacy violation.

If you really could previously and unable now, then IG has clearly closed the loophole.
