### ISSUE TITLE
About Livestream Replays

### ISSUE THREAD

**Issue by AcidV** [taengstagram/instagram-livestream-downloader#12]
## Please read the following instructions carefully

- Issues submitted without this template format will be **ignored**.
- I can't help you with python / ffmpeg installation problems so issues related to those will probably not get a response from me.
- Please read the questions asked and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] - no spaces).
- Do not post screenshots of text errors or logs.
- Use the Preview tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [X] Read the [README](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/README.md)
- [X] Read the [FAQ](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/FAQ.md)
- [X] [Searched](https://github.com/taengstagram/instagram-livestream-downloader/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Make sure you have the latest version: v0.3.6

### Purpose of your issue:
- [ ] Bug report (problems/errors)
- [X] Question
- [X] Other

### For a bug report, you **must** include the command used and a complete output/error log.

Command:

```bash
# Paste your command here.
# Remember not to include sensitive info such as passwords. Example:
livestream_dl -u "myusername" -collectcomments -o "/path/to/dl_folder/" "myfavigacct"
```

Complete Output/Error Log:

```
# Paste the error/output log here
```

### Describe your issue

Hello there. First of all thanks a lot for the downloader! 
Instagram now has the feature of saving the livestream as a replay for anyone to see. There is no way to download those replays as for now, or at least none that i'm aware of. Are you planning to add downloading replays in future versions?

**Comment by bryan** [comment]
I also am curious about the road plan for this issue.

My guess is that it's in the works since the package that this depends on already has [replay supported](https://github.com/ping/instagram_private_api_extensions#live) and should be easier since it's not stitching files through a stream but rather downloading a file directly.

**Comment by taengstagram** [comment]
Possibly in a week or two.
