### ISSUE TITLE
how to assemble files with the command line?

### ISSUE THREAD

**Issue by ghost** [taengstagram/instagram-livestream-downloader#16]
# THIS PROJECT IS NO LONGER MAINTAINED BY THE OWNER.

## Please read the following instructions carefully

- Issues submitted without this template format will be **ignored**.
- I can't help you with python / ffmpeg installation problems so issues related to those will probably not get a response from me.
- Please read the questions asked and answer completely.
- Put an `x` into all the boxes [x] relevant to your issue (like so [x] - no spaces).
- Do not post screenshots of text errors or logs.
- Use the Preview tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/README.md)
- [x] Read the [FAQ](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/FAQ.md)
- [x] [Searched](https://github.com/taengstagram/instagram-livestream-downloader/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Make sure you have the latest version: v0.3.8

### Purpose of your issue:
- [ ] Bug report (problems/errors)
- [x] Question
- [ ] Other

### For a bug report, you **must** include the command used and a complete output/error log.

Command:

```bash
# Paste your command here.
# Remember not to include sensitive info such as passwords. Example:
livestream_dl -u "myusername" -collectcomments -o "/path/to/dl_folder/" "myfavigacct"
```

Complete Output/Error Log:

```
# Paste the error/output log here
```

### Describe your issue

Explanation of your issue goes here. Please make sure you describe the issue clearly and completely.

**Comment by dvingerh** [comment]
You can use the following command:

```
livestream_as "livestream_json_file.json" -o "livestream_fragments_folder" -f "output_file.mp4" --repair
```

For instance:
```
livestream_as "20170519_milliebobbybrown_17874686371071511-3.json" -o "20170519_milliebobbybrown_17874686371071511_downloads-3" -f "output.mp4" --repair
```

**Comment by ghost** [comment]
What to do if the json file is empty?

**Comment by dvingerh** [comment]
Then you cannot merge the video files, as far as I know.

**Comment by MrLahey** [comment]
When trying that command line I run into an error saying 

> Traceback (most recent call last):
>   File "C:\Python35-32\Scripts\livestream_as-script.py", line 11, in <module>
>     load_entry_point('instagram-livestream-downloader==0.3.8', 'console_scripts', 'livestream_as')()
>   File "c:\python35-32\lib\site-packages\livestream_dl\assemble.py", line 64, in main
>     raise ValueError('broadcast json file does not exist: %s' % args.broadcast_json_file)
> ValueError: broadcast json file does not exist: 20170906_lilychee__17874366541136151_live-1.json

Should I just assume this can't be fixed?

**Comment by dvingerh** [comment]
@MrLahey 

The error says that your broadcast JSON file cannot be found, make sure the path to the file is correct.
If you don't have a (valid) JSON file for the broadcast then you can't assemble the video.

**Comment by MrLahey** [comment]
Hmm, I still have the JSON from the broadcast however it was from a broadcast that crapped out at some point and created an error. Must be why I can't assemble the video. Already tried repairing it too using other issues here and didn't work. Oh well, just wanted to make sure I wasn't missing something.

**Comment by jpr0k99** [comment]
anybody have a solution to download in batches, and rebroadcast in realtime? i.e syndication to another account

**Comment by dvingerh** [comment]
@jpr0k99 You can download multiple streams by making a looping batch or bash script for each Instagram user.

Batch (Windows):
```batch
:loop
livestream_dl -u "username" -p "password" "iguser"
timeout 20 > nul
goto loop
```

Bash (Linux/UNIX):
```bash
while true
do 
    livestream_dl -u "username" -p "password" "iguser"
    sleep 20
done
```

AFAIK there is no way to rebroadcast to another account.

**Comment by taengstagram** [comment]
This repo is not maintained but I've left issues open so that users can try to help each other. Please try and close your own issue if it is resolved. Thanks.
