### ISSUE TITLE
[SOLVED_ish]Change downloaded folder location.

### ISSUE THREAD

**Issue by NeoFahrenheit** [taengstagram/instagram-livestream-downloader#17]
In my computer, it allways stays at C:\Windows\SysWOW64\downloaded.
Is that normal? Can I change it?
Thanks!

**SOLVEDish:** From the Advance Usage Options:
livestream_dl -u "myloginusername" -outputdir "C:\instagram_live_downloads\" "myfavigacct"
saves downloads to C:\instagram_live_downloads\

**Comment by taengstagram** [comment]
This repo is not maintained but I've left issues open so that users can try to help each other. Please try and close your own issue if it is resolved. Thanks.
