### ISSUE TITLE
Fetch users comments on live stream videos

### ISSUE THREAD

**Issue by NabiKAZ** [taengstagram/instagram-livestream-downloader#19]
Thanks for good script.
Does can we fetch and have users comments on live stream videos as any files?
Does have be any access to these comments?
What's your solution for access it?
In another step, If can be marge users comment with video by ffmpeg, it's great!

**Comment by ghost** [comment]
Refer to the [Advance Usage Options](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/ADVANCE_USAGE.md). It creates a .SRT file with a timestamp alongside the comment. 

Check issue #10, too

**Comment by NabiKAZ** [comment]
@batman, Thanks and sorry for bad search before this.
