### ISSUE TITLE
Max resolution?

### ISSUE THREAD

**Issue by DreamCatcher0107** [taengstagram/instagram-livestream-downloader#2]
## Please read the following instructions carefully

- Issues submitted without this template format will be **ignored**.
- I can't help you with python / ffmpeg installation problems so issues related to those will probably not get a response from me.
- Please read the questions asked and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] - no spaces).
- Do not post screenshots of text errors or logs.
- Use the Preview tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/README.md)
- [x] Read the [FAQ](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/FAQ.md)
- [x] [Searched](https://github.com/taengstagram/instagram-livestream-downloader/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Make sure you have the latest version: v0.2.6

### Purpose of your issue:
- [ ] Bug report (problems/errors)
- [x] Question
- [ ] Other

### For a bug report, you **must** include the command used and a complete output/error log.

Command:

```bash
# Paste your command here.
# Remember not to include sensitive info such as passwords. Example:
livestream_dl -u "myusername" -collectcomments -o "/path/to/dl_folder/" "myfavigacct"
```

Complete Output/Error Log:

```
# Paste the error/output log here
```

### Describe your issue

// Moved my question from tumblr to here. Didn't notice the P/S, my apologies.
I've fully installed the downloader and have tried on a few livestreams. I noticed that sometimes the downloader downloads in max resolution but other times only in 396x704. Is there a possibility of including a command to always download the max res? Thank you.

**Comment by taengstagram** [comment]
Instagram for whatever reason, doesn't always provide a higher resolution stream. If a higher res stream doesn't exist, the downloader will just use the standard available stream which, as you've noticed, is just 396x704.

You can verify this for the stream you downloaded by checking the accompanying ``.json`` file that was generated along with the mp4. Open that file in any text editor, look for ``dash_abr_playback_url``

```
"dash_abr_playback_url": null,  # or a url like "https://scontent-xxx-1.cdninstagram.com/..."
```
if ``dash_abr_playback_url`` value is ``null`` (not a url), it means that at the time of the stream, there wasn't a better quality option available.

**Comment by DreamCatcher0107** [comment]
Alright, understood. Checked on a few streams and got the same null result for streams in 386x704. Much thanks!
