### ISSUE TITLE
Possibility of making livestream_dl run recursively?

### ISSUE THREAD

**Issue by ghost** [taengstagram/instagram-livestream-downloader#4]
### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/README.md)
- [x] Read the [FAQ](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/FAQ.md)
- [x] [Searched](https://github.com/taengstagram/instagram-livestream-downloader/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Make sure you have the latest version: v0.2.8

### Purpose of your issue:
- [ ] Bug report (problems/errors)
- [x] Question
- [ ] Other

### Describe your issue

How can I run this to check a user recursively? Right now I've created a bash script which runs the command every 5 seconds, and have it backgrounding with tmux. 
Is it possible to create a flag which checks if the livestream is up every X seconds, or so?

**Comment by taengstagram** [comment]
The recommended way is to use a bash/batch script. What can the program do that you can't in a few short lines of bash?

**Comment by ghost** [comment]
Simple enough, thanks
