### ISSUE TITLE
ValueError: Invalid format string

### ISSUE THREAD

**Issue by nppht** [taengstagram/instagram-livestream-downloader#5]
## Please read the following instructions carefully

- Issues submitted without this template format will be **ignored**.
- I can't help you with python / ffmpeg installation problems so issues related to those will probably not get a response from me.
- Please read the questions asked and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] - no spaces).
- Do not post screenshots of text errors or logs.
- Use the Preview tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [Y ] Read the [README](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/README.md)
- [Y] Read the [FAQ](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/FAQ.md)
- [Y] [Searched](https://github.com/taengstagram/instagram-livestream-downloader/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [Y] Make sure you have the latest version: v0.2.9

### Purpose of your issue:
- [Y] Bug report (problems/errors)
- [Y] Question
- [ ] Other

### For a bug report, you **must** include the command used and a complete output/error log.

Command:

```bash
livestream_dl -u "myid" -p "<mypassword>" "livestreamid"
```

Complete Output/Error Log:

```
# Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python36-32\Scripts\live
stream_dl-script.py", line 11, in <module>
    load_entry_point('instagram-livestream-downloader==0.2.9', 'console_scripts'
, 'livestream_dl')()
  File "c:\users\***\appdata\local\programs\python\python36-32\lib\site-pac
kages\livestream_dl\__main__.py", line 5, in main
    run()
  File "c:\users\***\appdata\local\programs\python\python36-32\lib\site-pac
kages\livestream_dl\download.py", line 356, in run
    download_start_time = int(now.strftime('%s'))
ValueError: Invalid format string
```
 

### Describe your issue
I ever can download the video file
but I don't know what happened
I try to uninstall and install again
but it's still show 'ValueError: Invalid format string'
I see from other Issues and do the same thing
but it's still show the massage like that
i try to use the command 
``` livestream_dl -u "<username>" "<instagram-live-username>" ```
but I can't type or paste the password

and I have some question, how to make loop in .bat file
I try to search in google but I still don't understand
or can you tell me where I should start with

sorry for my english
and thank you very much that you make this :)

**Comment by taengstagram** [comment]
Thanks for reporting the error. I've fixed it in the latest version so please [update your install to v0.3.0](https://github.com/taengstagram/instagram-livestream-downloader#updating) and let me know if it solves the ValueError.

The program will prompt you to enter the password. In the latest version, you will see a prompt like this:
```
Type in the password for <username> and press "Enter"
(Your password will not show on screen): 
```
 Just type in your password and press enter. Nothing will appear on screen but it is okay.

Regarding the .bat file, I don't have a Windows machine so I can't offer you any advice. Maybe in the future if I have time and can borrow a Windows PC, I will write an example.

**Comment by dvingerh** [comment]
To make a loop in a batch file you can use this:

>cd c:\Livestream_dl\
:loop
livestream_dl -u "myid" -p "mypassword" "livestreamid"
timeout 10 > nul
goto loop

I recommend you to cd to the directory first where you also save the livestreams to as shown in the batch example. I've found that if you use a config file you'll need to cd to the directory where the config file is located before running the `livestream_dl` command.

**Comment by nppht** [comment]
**thanks for answer! thank you so much :D** 

now i can download
**but the result is mp4.tmp and m4a.tmp file**
it's ok, i can change it to .mp4 and . m4a and take it together
but it's have a way to fix it? 
(it's same as the first time that i download before i have that problem)

it was showed
`Assembling files....
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python36-32\Scripts\live
stream_dl-script.py", line 11, in <module>
    load_entry_point('instagram-livestream-downloader==0.3.0', 'console_scripts'
, 'livestream_dl')()
  File "c:\users\***\appdata\local\programs\python\python36-32\lib\site-pac
kages\livestream_dl\__main__.py", line 5, in main
    run()
  File "c:\users\***\appdata\local\programs\python\python36-32\lib\site-pac
kages\livestream_dl\download.py", line 528, in run
    dl.stitch(final_output, skipffmpeg=userconfig.skipffmpeg, cleartempfiles=(no
t userconfig.nocleanup))
  File "c:\users\***\appdata\local\programs\python\python36-32\lib\site-pac
kages\instagram_private_api_extensions\live.py", line 356, in stitch
    exit_code = subprocess.call(cmd)
  File "c:\users\***\appdata\local\programs\python\python36-32\lib\subproce
ss.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\***\appdata\local\programs\python\python36-32\lib\subproce
ss.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\users\***\appdata\local\programs\python\python36-32\lib\subproce
ss.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

 
about the batch file 
**it's WORK !!!!**
/ for download from many id i can make many .bat file right?
or it have easier way?


thank you again :D ♥ 
(and sorry for my poor english lol)

**Comment by dvingerh** [comment]
Yes you can just have multiple batch files running at once, one for each id.

**Comment by ping** [comment]
@nppht Did you install ffmpeg? From the command line, what happens when you enter ``ffmpeg``?

If you run batches for multiple user IDs, you **must** increase the timeout number proportionally or you will get blocked from Instagram.

**Comment by taengstagram** [comment]
@nppht It looks like you don't have ffmpeg installed, or if you did, you did not set it properly in %PATH%.

May be this will help http://adaptivesamples.com/how-to-install-ffmpeg-on-windows/

For the batch file, the easiest way is probably to just add lines for each additional user.

```
cd c:\Livestream_dl
:loop
livestream_dl -u "myid" -p "mypassword" "livestreamid1"
timeout 10 > nul
livestream_dl -u "myid" -p "mypassword" "livestreamid2"
timeout 10 > nul
livestream_dl -u "myid" -p "mypassword" "livestreamid3"
timeout 10 > nul
goto loop
```

**Comment by nppht** [comment]
@ping thanks for tell me about batch files!
now I make new account so my main account (maybe) don't get blocked from ig 😂

@taengstagram I forget to add it to the patch!!
now I can download as mp4 file!!
thanks!!

- - - - - - - - - -

(**maybe** this is the (2+) last question) 
for batch file, if 2 user do the live in the same time (I mean in 1 batch file)
it will have problem?
or is better if I make many batch file?

and if I increase the timeout it will be missed at the first part of livestream right?
(maybe it's just 4-5 second? I just ask for sure)

- - - - - - - - - -

thank you so so so much !! ♥ 
and sorry again for my poor english

**Comment by taengstagram** [comment]
The IG block is not a block on your account, it's a temporary block on your IP address for about 15-30 minutes (can't remember exactly). So even if you switch to another account, as long as you're on the same IP, you won't be able to access IG at all until the block has ended.

If you have 2 or more users in one .bat file, the later user's stream will be downloaded when the earlier user's stream has ended.

If you increase the timeout, yes, you may miss more of the initial stream. There are always limits, if you want to check more users, you must increase the timeout. If you don't want to miss too much of a stream, don't check so many users.

The minimum safe timeout is 5 seconds. So if you use 2 .bat files, you must make timeout in each .bat file be 2*5 = 10 seconds.

For example: You have 3 .bat files running, so each .bat must have 3*5 = 15 seconds timeout

```
cd c:\Livestream_dl
:loop
livestream_dl -u "myid" -p "mypassword" "livestreamid3"
timeout 15 > nul
goto loop
```
