### ISSUE TITLE
Failed to Assembling Files

### ISSUE THREAD

**Issue by lordzuqi** [taengstagram/instagram-livestream-downloader#7]
## Please read the following instructions carefully

- Issues submitted without this template format will be **ignored**.
- I can't help you with python / ffmpeg installation problems so issues related to those will probably not get a response from me.
- Please read the questions asked and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] - no spaces).
- Do not post screenshots of text errors or logs.
- Use the Preview tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ ] Read the [README](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/README.md)
- [ ] Read the [FAQ](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/FAQ.md)
- [ ] [Searched](https://github.com/taengstagram/instagram-livestream-downloader/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] Make sure you have the latest version: v0.3.0

### Purpose of your issue:
- [ ] Bug report (problems/errors)
- [x] Question
- [ ] Other

### For a bug report, you **must** include the command used and a complete output/error log.

Command:

```bash
livestream_dl -u "myusername"  -o "d:\InstaLive" "myfavigacct"
```
Complete Output/Error Log:

```
Recorded stream is missing 863 seconds
Assembling files....
Traceback (most recent call last):
  File "C:\Phyton36\Scripts\livestream_dl-script.py", line 11, in <module>
    load_entry_point('instagram-livestream-downloader==0.3.0', 'console_scripts', 'livestream_dl')()

  File "c:\phyton36\lib\site-packages\livestream_dl\__main__.py", line 5, in main
    run()
  File "c:\phyton36\lib\site-packages\livestream_dl\download.py", line 528, in run
    dl.stitch(final_output, skipffmpeg=userconfig.skipffmpeg, cleartempfiles=(not userconfig.noclean
up))
  File "c:\phyton36\lib\site-packages\instagram_private_api_extensions\live.py", line 356, in stitch

    exit_code = subprocess.call(cmd)
  File "c:\phyton36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\phyton36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\phyton36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

### Describe your issue

Hi, I've tried to download livestream, but it always failed to assembled files after livestream finished.
theres tons of .m4v an .m4a files on my folder but, it didnt assembled to final video file.
what did I do wrong ?
thank you

**Comment by taengstagram** [comment]
It looks like you don't have ffmpeg installed, or if you did, you did not set it properly in %PATH%.

May be this will help http://adaptivesamples.com/how-to-install-ffmpeg-on-windows/

To verify if ffmpeg is properly installed, enter this in the Command Line:

```
ffmpeg -version
```

**Comment by lordzuqi** [comment]
it works !
I did had installed ffmpeg before, but seems like the PATH was the problem for me.
thank you. :D
