### ISSUE TITLE
Default timeout values?

### ISSUE THREAD

**Issue by dvingerh** [taengstagram/instagram-livestream-downloader#9]
## Please read the following instructions carefully

- Issues submitted without this template format will be **ignored**.
- I can't help you with python / ffmpeg installation problems so issues related to those will probably not get a response from me.
- Please read the questions asked and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] - no spaces).
- Do not post screenshots of text errors or logs.
- Use the Preview tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/README.md)
- [x] Read the [FAQ](https://github.com/taengstagram/instagram-livestream-downloader/blob/master/FAQ.md)
- [x] [Searched](https://github.com/taengstagram/instagram-livestream-downloader/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Make sure you have the latest version: v0.3.1

### Purpose of your issue:
- [ ] Bug report (problems/errors)
- [x] Question
- [ ] Other

### Describe your issue

What are the default values for `mpdtimeout` and `downloadtimeout` when they're not set in `livestream_dl.cfg` or specified in the command that's being ran ?

**Comment by taengstagram** [comment]
It is stated in help ``livestream_dl -h``. Units are in seconds.

```bash
  -mpdtimeout MPDTIMEOUT
                        Set timeout interval for mpd download.
                        Default 2.
  -downloadtimeout DOWNLOADTIMEOUT
                        Set timeout interval for segments download.
                        Default 15.
```
